services:
  # Service 1: The AI Trading Bot (Worker)
  - type: worker
    name: ai-trading-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "py train_model.py && py main.py"
    envVars:
      - fromGroup: ai-trading-bot-env

  # Service 2: The Web Dashboard (Web Service)
  - type: web
    name: ai-trading-dashboard
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn ai_bot_dashboard.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - fromGroup: ai-trading-bot-env
