services:
  # Service 1: The Web Interface (FastAPI)
  # Triggering a new deployment
  - type: web
    name: trading-bot-web
    env: python
    buildCommand: "pip install -r requirements.txt"
    # Use uvicorn directly, which is simpler and more standard for FastAPI.
    # It correctly binds to the PORT provided by Render.
    startCommand: "uvicorn web.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - fromGroup: trading-bot-env
# It is recommended to manage secrets directly in the Render dashboard
# rather than defining them in the render.yaml file.
# This envVarGroups section is removed to encourage best practices.
# The user should create an environment group named 'trading-bot-env' in Render.
