services:
  # Service 1: The Web Interface (FastAPI)
  # Triggering a new deployment
  - type: web
    name: trading-bot-web
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn web.main:app -w 1 -k uvicorn.workers.UvicornWorker --timeout 120 -b 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - fromGroup: trading-bot-env


envVarGroups:
  - name: trading-bot-env
    envVars:
      - key: BINANCE_API_KEY
        value: YOUR_BINANCE_API_KEY
      - key: BINANCE_API_SECRET
        value: YOUR_BINANCE_API_SECRET
      - key: TELEGRAM_BOT_TOKEN
        value: YOUR_TELEGRAM_BOT_TOKEN
      - key: TELEGRAM_CHAT_ID
        value: YOUR_TELEGRAM_CHAT_ID
      - key: SYMBOL
        value: XLM/USDT
      - key: TIMEFRAME
        value: 5m
      - key: STOP_LOSS_PERCENT
        value: 1.5
      - key: TAKE_PROFIT_PERCENT
        value: 3.0
      - key: POLL_SECONDS
        value: 10
      - key: DRY_RUN
        value: True
      - key: LOG_LEVEL
        value: INFO
