services:
  # A single Web Service to run everything for the free tier
  - type: web
    name: ai-trading-bot-suite
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn ai_bot_dashboard.dashboard:app --host 0.0.0.0 --port 10000"
    envVars:
      - fromGroup: ai-trading-bot-env
    healthCheckPath: / # The dashboard's root URL can serve as a health check
